### ISSUE TITLE
RemoteCommand(): 'unicode' object is not callable

### ISSUE THREAD

**Issue by sprive** [xolox/python-executor#5]
Hello,

I'm attempting to modify the example "Running remote commands" to utilize RSA key logins. I understood that this argument is documented under RemoteCommand()

```>>> from executor.ssh.client import RemoteCommand
>>> cmd = RemoteCommand('100.88.x.x', 'echo $SSH_CONNECTION', capture=True, ssh_user="ubuntu", identity_file="/home/sprive/key.pem")
>>> cmd.start()
>>> cmd.start()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'unicode' object is not callable
```

The above happened once, and hasn't repeated, but as I'm considering this to replace my own wrappers around Paramiko, I would like to understand...

I tried a second time in a new Python session:
```
>>> from executor.ssh.client import RemoteCommand
>>> cmd = RemoteCommand('100.88.x.x', 'echo $SSH_CONNECTION', ssh_user="ubuntu", identity_file="/home/sprive/key.pem")
>>> cmd.start()
100.88.x.x 43130 100.88.y.y 22
Connection to 100.88.y.y closed.
>>> cmd.output()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'NoneType' object is not callable
>>>
```

Some success but connection closes before I can call output(). 

I've repeated above =using other commands, like 'hostname' and 'whoami', with same pattern (closes after start() ).

The environment is EC2, if that matters. From that source PC (as user sprive) I can do a Bash one-liner to SSH to ubuntu@target and get successful output:
```
$ ssh ubuntu@100.88.y.y -i /home/sprive/key.pem "whoami"
ubuntu
```

Oddly, if I replace the command with 'echo $SSH_CONNECTION' I get empty output.  However the connection is actually . I can show this by changing the command to 'echo $SSH_CONNECTION; touch /tmp/xyz' then checking /tmp/xyz. I don't really think this is relevant, but since the example uses $SSH_CONNECTION as indication of success I am mentioning it.

Thoughts?

**Comment by FooBarQuaxx** [comment]
Output is an attribute and not a method. And I guess on the first console session in this issue, you've run `cmd.output()` and not `cmd.start()` twice.

**Comment by sprive** [comment]
ack, agree it probably was user error in understanding docs or trying to adapt examples.
Will close.
